# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-02 11:13
from __future__ import unicode_literals

import agency_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonead', models.CharField(max_length=100, null=True)),
                ('adimage', models.ImageField(blank=True, null=True, upload_to=agency_app.models.generate_add_dir, verbose_name='заглавное изображенe')),
            ],
            options={
                'verbose_name': 'рекламу',
                'verbose_name_plural': 'реклама',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('phone', models.CharField(max_length=22, verbose_name='телефон')),
                ('email', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'агента',
                'verbose_name_plural': 'агенты',
            },
        ),
        migrations.CreateModel(
            name='Appointement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(max_length=100, verbose_name='назначение')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'назначение',
                'verbose_name_plural': 'назначение',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('icon', models.FileField(blank=True, null=True, upload_to=agency_app.models.generate_icon, verbose_name='иконка категории')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='город')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=agency_app.models.dir_images, verbose_name='изображеня')),
                ('dir_img', models.CharField(default='81581', max_length=50, verbose_name='название папки')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='название страницы')),
                ('slug', models.SlugField()),
                ('service_title', models.CharField(max_length=100, null=True, verbose_name='заголовок')),
                ('service_text', models.TextField(max_length=100, null=True, verbose_name='описание')),
                ('icon', models.CharField(max_length=100, null=True, verbose_name='иконка для раздела')),
            ],
            options={
                'verbose_name': 'страницу',
                'verbose_name_plural': 'страница',
            },
        ),
        migrations.CreateModel(
            name='PartnerStok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True, verbose_name='компания')),
                ('company_url', models.URLField(blank=True, null=True, verbose_name='сайт компании')),
                ('condition', models.CharField(blank=True, max_length=220, null=True, verbose_name='описание')),
                ('amount', models.DateTimeField(verbose_name='срок действия акции до/')),
                ('tag', models.TextField(default='tagstock')),
            ],
            options={
                'verbose_name': 'скидку',
                'verbose_name_plural': 'скидки',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prop', models.CharField(blank=True, default='81581', max_length=150, null=True, verbose_name='id объекта/папки')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name='улица')),
                ('hnum', models.CharField(blank=True, max_length=350, verbose_name='номер дома')),
                ('romm', models.CharField(blank=True, max_length=200, verbose_name='кол-во комнат')),
                ('title', models.CharField(max_length=600, verbose_name='заголовок')),
                ('slug', models.SlugField()),
                ('desc', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=agency_app.models.generate_filename, verbose_name='заглавное изображенe')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='дата публикации')),
                ('status', models.BooleanField(verbose_name='рекламировать')),
                ('area', models.PositiveIntegerField(default=0, verbose_name='метраж')),
                ('areafield', models.PositiveIntegerField(default=0, verbose_name='площадь')),
                ('flor', models.PositiveIntegerField(default=1, verbose_name='этажи')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='стоимость')),
                ('saler', models.CharField(blank=True, max_length=150, verbose_name='продавец')),
                ('salerphone', models.CharField(blank=True, max_length=150, verbose_name='телефон продавца')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency_app.Agent', verbose_name='агент')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency_app.Appointement', verbose_name='назначение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_app.Category', verbose_name='категоря')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency_app.City', verbose_name='город')),
                ('stok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agency_app.PartnerStok', verbose_name='акция')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
            },
        ),
        migrations.CreateModel(
            name='Qeustions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=300, null=True, verbose_name='вопрос')),
                ('answer', models.CharField(max_length=300, null=True, verbose_name='ответ')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_app.Property'),
        ),
    ]
