# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-02 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area_field',
            new_name='areafield',
        ),
    ]
