# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-02 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='dir_img',
            field=models.CharField(default='30782', max_length=50, verbose_name='название папки'),
        ),
        migrations.AlterField(
            model_name='property',
            name='id_prop',
            field=models.CharField(blank=True, default='30782', max_length=150, null=True, verbose_name='id объекта/папки'),
        ),
    ]
