# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-08 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_app', '0004_auto_20180907_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertystatistic',
            options={'verbose_name': 'статистика', 'verbose_name_plural': 'статистика'},
        ),
        migrations.AddField(
            model_name='property',
            name='coun',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='images',
            name='dir_img',
            field=models.CharField(default='35970', max_length=50, verbose_name='название папки'),
        ),
        migrations.AlterField(
            model_name='property',
            name='id_prop',
            field=models.CharField(blank=True, default='35970', max_length=150, null=True, verbose_name='id объекта/папки'),
        ),
    ]
